from incident_types import (
    ActionType,
    HelpfulAction,
    RequiredAction,
    ScenarioConfig,
    ServiceMetrics,
)


def get_scenario() -> ScenarioConfig:
    return ScenarioConfig(
        id="hard_cascade_failure",
        name="Cache Deploy Cascade Failure",
        difficulty="hard",
        alert="SEV-1: Checkout 5xx storm with p99 latency regression and saturation alerts across prod-us-east-1.",
        services=["api", "db", "cache", "worker", "ingress"],
        max_steps=15,
        root_cause="cache outage caused db saturation and api failure",
        root_cause_aliases=[
            "cache outage cascade",
            "cache to db to api cascade",
            "cache failure cascade",
            "cache primary unavailable",
            "cascade failure",
        ],
        initial_visible_services=["api", "ingress", "worker"],
        initial_visible_logs=[
            "api: ERROR request_id=5d3f4 route=/checkout upstream timeout after 2000ms",
            "ingress: WARN 502 surge detected for route=checkout-api",
            "worker: WARN retry budget nearing threshold for write jobs",
            "ingress: INFO regional traffic volume baseline unchanged (+1.8% vs 1h avg)",
        ],
        hidden_logs={
            "api": [
                "api: WARN cache fallback activated; redirecting reads to primary database",
                "api: ERROR db connection pool exhausted during fallback path",
                "api: WARN circuit-breaker state flapping between open and half-open",
                "api: INFO error rate starts dropping after cache pool recovers",
            ],
            "cache": [
                "cache: ERROR primary shard startup failed: incompatible module binary after rollout",
                "cache: FATAL no healthy masters available for slot range 0-5460",
                "cache: WARN client reconnect storm throttled by backoff",
                "cache: INFO shard process recovered and accepting client traffic",
            ],
            "db": [
                "db: ERROR too many clients already; max_connections threshold reached",
                "db: WARN active transactions dominated by cache-miss fallback queries",
                "db: INFO replication healthy; no disk or WAL bottleneck detected",
                "db: INFO connection pressure decreasing after upstream cache recovery",
            ],
            "worker": [
                "worker: INFO background compaction job running (non-blocking)",
                "worker: WARN dead-letter queue growth due to API write failures",
                "worker: INFO dead-letter trend reverses after API success rate recovers",
            ],
            "ingress": [
                "ingress: INFO traffic volume normal; anomaly isolated to downstream service health",
                "ingress: WARN short-lived TLS handshake spike on unrelated route resolved automatically",
            ],
        },
        metrics={
            "api": ServiceMetrics(
                cpu_pct=89.0,
                memory_pct=91.0,
                latency_ms=1860.0,
                error_rate=0.68,
                rps=470.0,
            ),
            "db": ServiceMetrics(
                cpu_pct=94.0,
                memory_pct=82.0,
                latency_ms=640.0,
                error_rate=0.34,
                rps=720.0,
            ),
            "cache": ServiceMetrics(
                cpu_pct=11.0,
                memory_pct=37.0,
                latency_ms=6.0,
                error_rate=0.96,
                rps=42.0,
            ),
            "worker": ServiceMetrics(
                cpu_pct=47.0,
                memory_pct=53.0,
                latency_ms=122.0,
                error_rate=0.12,
                rps=205.0,
            ),
            "ingress": ServiceMetrics(
                cpu_pct=35.0,
                memory_pct=45.0,
                latency_ms=72.0,
                error_rate=0.36,
                rps=910.0,
            ),
        },
        required_actions=[
            RequiredAction(action=ActionType.CHECK_LOGS, service="api"),
            RequiredAction(action=ActionType.CHECK_LOGS, service="cache"),
            RequiredAction(action=ActionType.CHECK_METRICS, service="cache"),
            RequiredAction(action=ActionType.CHECK_METRICS, service="db"),
            RequiredAction(action=ActionType.RESTART_SERVICE, service="cache"),
            RequiredAction(action=ActionType.RESTART_SERVICE, service="db"),
            RequiredAction(action=ActionType.ROLLBACK_DEPLOYMENT),
            RequiredAction(action=ActionType.DECLARE_ROOT_CAUSE),
        ],
        helpful_actions=[
            HelpfulAction(action=ActionType.CHECK_LOGS, service="api"),
            HelpfulAction(action=ActionType.CHECK_LOGS, service="cache"),
            HelpfulAction(action=ActionType.CHECK_LOGS, service="db"),
            HelpfulAction(action=ActionType.CHECK_LOGS, service="ingress"),
            HelpfulAction(action=ActionType.CHECK_METRICS, service="cache"),
            HelpfulAction(action=ActionType.CHECK_METRICS, service="db"),
            HelpfulAction(action=ActionType.CHECK_METRICS, service="api"),
            HelpfulAction(action=ActionType.RESTART_SERVICE, service="cache"),
            HelpfulAction(action=ActionType.RESTART_SERVICE, service="db"),
            HelpfulAction(action=ActionType.ROLLBACK_DEPLOYMENT),
            HelpfulAction(action=ActionType.DECLARE_ROOT_CAUSE),
        ],
        resolution_bonus=14.5,
        wrong_diagnosis_penalty=7.0,
    )
